### ISSUE TITLE
polygit is serving an old version of webcomponents-lite.js

### ISSUE THREAD

**Issue by bicknellr** [PolymerLabs/polygit#3]
Open http://polygit.org/components/webcomponentsjs/webcomponents-lite.js and search for `isIE11OrOlder`. This identifier should have been renamed by this commit: https://github.com/webcomponents/webcomponentsjs/commit/4346c37fec5fea8fd5a750be979ad76976b7bbb6.

**Comment by ebidel** [comment]
In fact it's serving 0.7.2. Current release is 0.7.15

**Comment by ebidel** [comment]
IDK if @sjmiles did something, but I moved the "latest release" to 0.7.15 yesterday (https://github.com/webcomponents/webcomponentsjs/releases). That might have done it.
